export interface ProfileDetails {
    email: string,
    user_name: string,
    first_name: string | null,
    middle_name: string | null,
    last_name: string | null,
    id_marital_status: string | null,
    birth_date: string | null,
    nationalities: string[],
    id_gender: string | null,
    phone_number: string | null,
    id_status: string,
    document_type: string | null,
    document_number: string | null,
    id_country: string | null,
    geographic_division_type: string | null,
    id_geographic_division: string | null,
    street: string | null,
    street_number: string | null,
    house_number: string | null,
    neighborhood: string | null,
    block: string | null,
    pathway: string | null,
    current: string | null,
    id_profile: string,
}